api:
  url: "https://api.coingecko.com/api/v3/coins/markets"
  wait_time: 60
  retry_time: 10
  params: 
    vs_currency: "usd"
    order: "market_cap_desc"
    per_page: 250
    page: 1

paths:
  data_dir: "data"
  checkpoint_dir: "checkpoints"

database:
  table_name: "crypto_data"

cloud:
  gcs_bucket_name: "big-data-project-bucket-123456"
  bq_dataset: "crypto_dataset"
  bq_table: "crypto_data"